version: "3"
services:
  facsvatar_bridge:
    build:
      context: .
      dockerfile: ./process_bridge/Dockerfile
    ports:
    - "5570:5570"  # map container internal 5550 port to publicly accessible 5550 port
    - "5571:5571"

  facsvatar_facstoblend:
    build:
      context: .
      dockerfile: ./process_facstoblend/Dockerfile
    ports:
      - "5572:5572"

  facsvatar_facsfromcsv:
    build:
      context: .  # Docker context from folder of this file; needed to include requirement.txt
      dockerfile: ./input_facsfromcsv/Dockerfile
    #stdin_open: true  # same as docker -i (interactive)
    #tty: true  # same as docker -t (tty); see if sub actually receives pub messages
    command: tail -F anything  # prevents closure of container when no command is running
